INSERT into tb_sys_qans (sysid, qid, answer) values (1,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,1,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,2,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (1,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,1,'13');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,3,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,2,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (3,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,1,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,2,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (5,8,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,1,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (7,8,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,1,'12');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,2,'14');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (18,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,1,'40');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,3,'6');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,2,'15');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (36,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,1,'12');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,2,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (46,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,1,'6');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,2,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (54,8,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,1,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (56,8,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,1,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (58,8,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,1,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,2,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (62,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,11,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,1,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,2,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,7,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (64,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,1,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,2,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (66,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,1,'15');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,3,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,2,'18');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (68,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,1,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (72,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,1,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,2,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (74,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,1,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,2,'7');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (76,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,1,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,3,'0');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,2,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,7,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (78,8,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,1,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,2,'9');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,7,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (82,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,1,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,2,'9');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (84,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,1,'12');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,2,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (86,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,1,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,2,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (90,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,1,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (92,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,1,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,3,'0');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (94,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,1,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,2,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (96,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,1,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (98,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,1,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (100,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,1,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,2,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (102,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,1,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,2,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (104,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,1,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (106,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,1,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,2,'9');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (108,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,1,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,2,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (110,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,1,'6');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,3,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,2,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (112,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,1,'10');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,2,'14');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,7,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (114,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,1,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,7,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (116,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,1,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,3,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,2,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (118,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,1,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,7,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (120,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,1,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,2,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (122,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,1,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,3,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,2,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (124,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,1,'24');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,3,'7');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,2,'30');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (126,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,1,'6');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,2,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (128,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,10,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,1,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,3,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,2,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,5,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,4,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (130,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,12,'Akshaya Patra');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,1,'15');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,3,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,2,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,9,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (132,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,1,'14');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,3,'6');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,2,'11');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,6,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (134,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,10,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,12,'Other');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,1,'16');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,3,'04');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,2,'17');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,5,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,4,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,7,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,6,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,9,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (136,8,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,10,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,1,'No');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (140,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (142,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (142,12,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (142,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (142,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (142,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (142,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (142,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,12,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (144,8,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (146,11,'Yes');
INSERT into tb_sys_qans (sysid, qid, answer) values (146,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (146,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (146,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (146,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (146,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (146,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (148,12,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (148,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (148,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (148,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (148,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (148,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (148,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (150,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (150,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (150,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (150,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (150,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (150,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (150,8,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (152,12,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (152,15,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (152,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (152,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (152,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (152,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (152,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (154,12,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (154,15,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (154,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (154,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (154,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (154,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (154,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (156,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (156,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (156,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (156,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (156,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (156,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (156,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (158,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (158,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (158,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (158,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (158,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (158,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (158,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (160,12,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (160,15,'6');
INSERT into tb_sys_qans (sysid, qid, answer) values (160,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (160,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (160,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (160,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (160,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (162,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (162,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (162,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (162,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (162,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (162,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (162,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (164,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (164,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (164,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (164,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (164,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (164,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (164,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (166,12,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (166,15,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (166,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (166,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (166,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (166,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (166,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (168,12,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (168,15,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (168,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (168,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (168,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (168,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (168,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (170,12,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (170,15,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (170,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (170,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (170,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (170,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (170,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (172,12,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (172,15,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (172,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (172,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (172,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (172,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (172,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (174,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (174,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (174,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (174,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (174,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (174,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (176,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (176,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (176,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (176,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (176,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (176,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (176,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (178,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (178,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (178,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (178,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (178,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (178,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (178,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (180,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (180,15,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (180,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (180,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (180,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (180,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (182,12,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (182,15,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (182,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (182,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (182,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (182,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (184,12,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (184,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (184,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (184,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (184,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (184,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (184,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (186,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (186,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (186,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (186,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (186,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (192,12,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (192,15,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (192,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (192,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (192,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (192,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (194,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (194,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (194,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (194,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (194,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (194,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (196,12,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (196,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (196,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (196,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (196,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (196,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (196,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (204,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (204,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (204,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (204,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (204,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (204,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (204,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (206,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (206,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (206,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (206,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (206,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (206,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (206,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (208,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (208,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (208,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (208,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (208,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (208,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (208,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (188,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (188,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (188,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (188,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (188,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (188,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (190,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (190,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (190,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (190,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (190,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (190,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (190,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (198,12,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (198,15,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (198,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (198,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (198,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (198,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (198,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (200,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (200,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (200,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (200,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (200,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (200,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (200,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (202,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (202,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (202,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (202,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (202,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (202,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (202,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (210,12,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (210,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (210,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (210,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (210,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (210,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (210,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (212,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (212,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (212,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (212,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (212,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (212,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (212,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (214,12,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (214,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (214,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (214,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (214,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (214,8,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (216,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (216,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (216,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (216,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (216,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (216,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (218,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (218,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (218,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (218,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (218,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (218,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (218,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (220,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (220,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (220,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (220,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (220,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (220,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (220,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (222,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (222,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (222,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (222,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (222,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (222,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (222,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (224,12,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (224,15,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (224,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (224,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (224,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (224,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (224,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (226,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (226,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (226,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (226,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (226,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (226,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (228,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (228,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (228,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (228,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (228,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (228,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (230,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (230,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (230,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (230,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (230,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (232,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (232,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (232,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (232,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (232,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (234,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (234,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (234,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (234,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (234,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (234,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (236,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (236,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (236,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (236,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (236,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (236,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (236,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (238,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (238,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (238,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (238,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (238,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (238,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (238,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (240,12,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (240,15,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (240,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (240,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (240,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (240,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (240,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (242,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (242,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (242,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (242,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (242,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (242,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (242,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (244,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (244,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (244,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (244,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (244,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (244,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (244,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (246,12,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (246,15,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (246,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (246,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (246,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (246,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (246,8,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (248,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (248,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (248,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (248,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (248,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (248,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (248,8,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (250,12,'7');
INSERT into tb_sys_qans (sysid, qid, answer) values (250,15,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (250,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (250,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (250,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (250,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (250,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (252,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (252,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (252,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (252,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (252,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (252,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (252,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (254,12,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (254,15,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (254,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (254,7,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (254,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (254,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (254,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,10,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,12,'8');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,15,'9');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (256,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (258,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (258,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (258,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (258,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (258,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (258,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (258,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (260,12,'5');
INSERT into tb_sys_qans (sysid, qid, answer) values (260,15,'7');
INSERT into tb_sys_qans (sysid, qid, answer) values (260,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (260,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (260,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (260,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (260,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (262,12,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (262,15,'3');
INSERT into tb_sys_qans (sysid, qid, answer) values (262,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (262,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (262,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (262,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (264,12,'4');
INSERT into tb_sys_qans (sysid, qid, answer) values (264,15,'6');
INSERT into tb_sys_qans (sysid, qid, answer) values (264,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (264,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (264,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (264,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (264,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (266,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (266,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (266,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (266,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (266,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (266,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (266,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (268,12,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (268,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (268,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (268,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (268,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (268,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (268,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (270,12,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (270,15,'2');
INSERT into tb_sys_qans (sysid, qid, answer) values (270,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (270,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (270,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (270,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (270,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (276,12,'12');
INSERT into tb_sys_qans (sysid, qid, answer) values (276,15,'7');
INSERT into tb_sys_qans (sysid, qid, answer) values (276,3,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (276,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (276,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (276,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (276,8,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (278,12,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (278,15,'1');
INSERT into tb_sys_qans (sysid, qid, answer) values (278,3,'Not available');
INSERT into tb_sys_qans (sysid, qid, answer) values (278,7,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (278,6,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (278,9,'Available and functional');
INSERT into tb_sys_qans (sysid, qid, answer) values (278,8,'Available and functional');
